"""Add priority field to ToDo

Revision ID: 650c5c6e5830
Revises: 4f2858207b85
Create Date: 2025-08-31 20:40:09.618465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '650c5c6e5830'
down_revision = '4f2858207b85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_column('priority')

    # ### end Alembic commands ###
